### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by zhaoyongle1531** [chenyuntc/simple-faster-rcnn-pytorch#108]
when I run "python train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain"：

load data
model construct completed
WARNING:root:Setting up a new session...
5011it [22:44,  3.92it/s]
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    fire.Fire()
  File "/home/wz/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/wz/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/wz/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 106, in train
    eval_result = eval(test_dataloader, faster_rcnn, test_num=opt.test_num)
  File "train.py", line 30, in eval
    for ii, (imgs, sizes, gt_bboxes_, gt_labels_, gt_difficults_) in tqdm(enumerate(dataloader)):
  File "/home/wz/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "/home/wz/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 289, in __init__
    w.start()
  File "/home/wz/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/wz/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/wz/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/wz/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/wz/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
Please help me! 救救孩子吧！

**Comment by buaacarzp** [comment]
hey,its my honer to meet the same problem to you , i want to ask you that  you overcome this problem it or not, please help me , my qq number is:510695983, thank you.

**Comment by charles-wangzi** [comment]
I have the same question,please help me

**Comment by kangkang59812** [comment]
any one solve it ?

**Comment by neonb88** [comment]
One solution: [try changing](https://github.com/prlz77/ResNeXt.pytorch/issues/5) the `num_workers` variable passed into the `DataLoader`.  And if that doesn't work, try [adding more swap memory](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04).
