### ISSUE TITLE
Arraytool missing

### ISSUE THREAD

**Issue by joeybose** [chenyuntc/simple-faster-rcnn-pytorch#12]
Hi I tried to run the cool but it seems that array_tool.py is missing.

**Comment by chenyuntc** [comment]
it's [ here](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/master/utils/array_tool.py)
what  do you mean   'it's missing'?

**Comment by joeybose** [comment]
I ran the code as per the instructions and this the error I got: 
python train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain=False
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from model import FasterRCNNVGG16
  File "model/__init__.py", line 1, in <module>
    from .faster_rcnn_vgg16 import FasterRCNNVGG16
  File "model/faster_rcnn_vgg16.py", line 5, in <module>
    from model.faster_rcnn import FasterRCNN
  File "model/faster_rcnn.py", line 5, in <module>
    from utils import array_tool as at
ImportError: cannot import name array_tool

**Comment by joeybose** [comment]
Ok there's another utils inside the models folder which doesn't have array tools. A simple copy of files should fix the problem or changing the import directory. I'm not sure which is your preferred way to fix this.

**Comment by chenyuntc** [comment]
You're using python2?
try:
`from __future__ import absolute_import`

**Comment by joeybose** [comment]
After a couple of copies of files and forcing UTF-8 encoding i got it to work. Thanks! Now i'll try to extend this to other datasets like WIDER.
