### ISSUE TITLE
RuntimeError: expected type torch.DoubleTensor but got torch.FloatTensor

### ISSUE THREAD

**Issue by YunjieYu** [chenyuntc/simple-faster-rcnn-pytorch#131]
Hello, when I start to train, I get an error like this:

99it [01:56,  1.23s/it]Traceback (most recent call last):
  File "train.py", line 132, in <module>
    fire.Fire()
  File "/home/yunjieyu/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/yunjieyu/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/yunjieyu/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 98, in train
    _bboxes, _labels, _scores = trainer.faster_rcnn.predict([ori_img_], visualize=True)
  File "/home/yunjieyu/code/simple-faster-rcnn-pytorch/model/faster_rcnn.py", line 19, in new_f
    return f(*args,**kwargs)
  File "/home/yunjieyu/code/simple-faster-rcnn-pytorch/model/faster_rcnn.py", line 222, in predict
    img = preprocess(at.tonumpy(img))
  File "/home/yunjieyu/code/simple-faster-rcnn-pytorch/data/dataset.py", line 74, in preprocess
    return normalize(img)
  File "/home/yunjieyu/code/simple-faster-rcnn-pytorch/data/dataset.py", line 27, in pytorch_normalze
    img = normalize(t.from_numpy(img))
  File "/home/yunjieyu/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 163, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/yunjieyu/anaconda3/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: expected type torch.DoubleTensor but got torch.FloatTensor

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by YunjieYu** [comment]
What's the problem??  My environment is Ubuntu 16.04, Pytorch 1.0.1, python 3.6.

**Comment by BIGJUN777** [comment]
Hello, have you solved this problem yet?

Thank you!

**Comment by BIGJUN777** [comment]
Please refer to this [issue](https://github.com/pytorch/pytorch/issues/2138)
Get to the [code](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/6a538bdd113bab649f388aa48193c1b1ccc48ee6/data/dataset.py#L27), and call `.float()` on the input :
> img = normalize((t.from_numpy(img)).float())

**Comment by YunjieYu** [comment]
OK, I will try it. Thanks!
