### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by XGuider** [chenyuntc/simple-faster-rcnn-pytorch#141]
`Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.6/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/home/dell/.local/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/Desktop/AFA/Faster-Rcnn-Pytorch/simple-faster-rcnn-pytorch-master/train.py", line 12, in <module>
    from model import FasterRCNNVGG16
  File "/home/dell/Desktop/AFA/Faster-Rcnn-Pytorch/simple-faster-rcnn-pytorch-master/model/__init__.py", line 1, in <module>
    from model.faster_rcnn_vgg16 import FasterRCNNVGG16
  File "/home/dell/Desktop/AFA/Faster-Rcnn-Pytorch/simple-faster-rcnn-pytorch-master/model/faster_rcnn_vgg16.py", line 5, in <module>
    from model.region_proposal_network import RegionProposalNetwork
  File "/home/dell/Desktop/AFA/Faster-Rcnn-Pytorch/simple-faster-rcnn-pytorch-master/model/region_proposal_network.py", line 7, in <module>
    from model.utils.creator_tool import ProposalCreator
  File "/home/dell/Desktop/AFA/Faster-Rcnn-Pytorch/simple-faster-rcnn-pytorch-master/model/utils/creator_tool.py", line 2, in <module>
    import cupy as cp
  File "/home/dell/.local/lib/python3.6/site-packages/cupy/__init__.py", line 32, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/dell/.local/lib/python3.6/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/home/dell/.local/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html

original error: libcublas.so.9.0: cannot open shared object file: No such file or directory

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True`

**Comment by XGuider** [comment]
thank you work so much,hope you can solve this problem?

**Comment by youmu11** [comment]
the same question with you, sorry i can't solve it

**Comment by yifeichenNJ** [comment]
> thank you work so much,hope you can solve this problem?

how can i solve the same problem

**Comment by yifeichenNJ** [comment]
> the same question with you, sorry i can't solve it
do you solve the problem
