### ISSUE TITLE
expected backend CPU and dtype Double but got backend CPU and dtype Float

### ISSUE THREAD

**Issue by yangninghua** [chenyuntc/simple-faster-rcnn-pytorch#157]
解决方案：
pytorch1.1.0
data/dataset.py

```
class Config:
    # data
    voc_data_dir = '/home/spple/data/VOCdevkit/VOC2012/'
    min_size = 600  # image resize
    max_size = 1000 # image resize
    num_workers = 1
    test_num_workers = 1
```

```
from __future__ import  absolute_import
from __future__ import  division
import torch as t
from data.voc_dataset import VOCBboxDataset
from skimage import transform as sktsf
from torchvision import transforms as tvtsf
from data import util
import numpy as np
from utils.config import opt

# 0.2.0
import torch
def _is_tensor_image(img):
    return torch.is_tensor(img) and img.ndimension() == 3

def normalize(tensor, mean, std):
    """Normalize a tensor image with mean and standard deviation.
    See ``Normalize`` for more details.
    Args:
        tensor (Tensor): Tensor image of size (C, H, W) to be normalized.
        mean (sequence): Sequence of means for each channel.
        std (sequence): Sequence of standard deviations for each channely.
    Returns:
        Tensor: Normalized Tensor image.
    """
    if not _is_tensor_image(tensor):
        raise TypeError('tensor is not a torch image.')
    # TODO: make efficient
    for t, m, s in zip(tensor, mean, std):
        t.sub_(m).div_(s)
    return tensor
class Normalize_2_0(object):
    """Normalize an tensor image with mean and standard deviation.
    Given mean: ``(M1,...,Mn)`` and std: ``(S1,..,Sn)`` for ``n`` channels, this transform
    will normalize each channel of the input ``torch.*Tensor`` i.e.
    ``input[channel] = (input[channel] - mean[channel]) / std[channel]``
    Args:
        mean (sequence): Sequence of means for each channel.
        std (sequence): Sequence of standard deviations for each channel.
    """
    def __init__(self, mean, std):
        self.mean = mean
        self.std = std

    def __call__(self, tensor):
        """
        Args:
            tensor (Tensor): Tensor image of size (C, H, W) to be normalized.
        Returns:
            Tensor: Normalized Tensor image.
        """
        return normalize(tensor, self.mean, self.std)

# 0.3.0
# import torch
# def _is_tensor_image(img):
#     return torch.is_tensor(img) and img.ndimension() == 3
# def normalize(tensor, mean, std, inplace=False):
#     """Normalize a tensor image with mean and standard deviation.
#     .. note::
#         This transform acts out of place by default, i.e., it does not mutates the input tensor.
#     See :class:`~torchvision.transforms.Normalize` for more details.
#     Args:
#         tensor (Tensor): Tensor image of size (C, H, W) to be normalized.
#         mean (sequence): Sequence of means for each channel.
#         std (sequence): Sequence of standard deviations for each channel.
#     Returns:
#         Tensor: Normalized Tensor image.
#     """
#     if not _is_tensor_image(tensor):
#         raise TypeError('tensor is not a torch image.')
#
#     if not inplace:
#         tensor = tensor.clone()
#
#     mean = torch.as_tensor(mean, dtype=torch.float32, device=tensor.device)
#     std = torch.as_tensor(std, dtype=torch.float32, device=tensor.device)
#     tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
#     return tensor
# class Normalize_3_0(object):
#     """Normalize a tensor image with mean and standard deviation.
#     Given mean: ``(M1,...,Mn)`` and std: ``(S1,..,Sn)`` for ``n`` channels, this transform
#     will normalize each channel of the input ``torch.*Tensor`` i.e.
#     ``input[channel] = (input[channel] - mean[channel]) / std[channel]``
#     .. note::
#         This transform acts out of place, i.e., it does not mutates the input tensor.
#     Args:
#         mean (sequence): Sequence of means for each channel.
#         std (sequence): Sequence of standard deviations for each channel.
#     """

#     def __init__(self, mean, std, inplace=False):
#         self.mean = mean
#         self.std = std
#         self.inplace = inplace

#     def __call__(self, tensor):
#         """
#         Args:
#             tensor (Tensor): Tensor image of size (C, H, W) to be normalized.
#         Returns:
#             Tensor: Normalized Tensor image.
#         """
#         return normalize(tensor, self.mean, self.std, self.inplace)

#     def __repr__(self):
#         return self.__class__.__name__ + '(mean={0}, std={1})'.format(self.mean, self.std)



def inverse_normalize(img):
    if opt.caffe_pretrain:
        img = img + (np.array([122.7717, 115.9465, 102.9801]).reshape(3, 1, 1))
        return img[::-1, :, :]
    # approximate un-normalize for visualize
    return (img * 0.225 + 0.45).clip(min=0, max=1) * 255


def pytorch_normalze(img):
    """
    https://github.com/pytorch/vision/issues/223
    return appr -1~1 RGB
    """
    _normalize = Normalize_2_0(mean=[0.485, 0.456, 0.406],
                                std=[0.229, 0.224, 0.225])
    img = _normalize(t.from_numpy(img))
    return img.numpy()


def caffe_normalize(img):
    """
    return appr -125-125 BGR
    """
    img = img[[2, 1, 0], :, :]  # RGB-BGR
    img = img * 255
    mean = np.array([122.7717, 115.9465, 102.9801]).reshape(3, 1, 1)
    img = (img - mean).astype(np.float32, copy=True)
    return img


def preprocess(img, min_size=600, max_size=1000):
    """Preprocess an image for feature extraction.

    The length of the shorter edge is scaled to :obj:`self.min_size`.
    After the scaling, if the length of the longer edge is longer than
    :param min_size:
    :obj:`self.max_size`, the image is scaled to fit the longer edge
    to :obj:`self.max_size`.

    After resizing the image, the image is subtracted by a mean image value
    :obj:`self.mean`.

    Args:
        img (~numpy.ndarray): An image. This is in CHW and RGB format.
            The range of its value is :math:`[0, 255]`.

    Returns:
        ~numpy.ndarray: A preprocessed image.

    """
    C, H, W = img.shape
    scale1 = min_size / min(H, W)
    scale2 = max_size / max(H, W)
    scale = min(scale1, scale2)
    img = img / 255.
    img = sktsf.resize(img, (C, H * scale, W * scale), mode='reflect',anti_aliasing=False)
    # both the longer and shorter should be less than
    # max_size and min_size
    if opt.caffe_pretrain:
        normalize = caffe_normalize
    else:
        normalize = pytorch_normalze
    return normalize(img)


class Transform(object):

    def __init__(self, min_size=600, max_size=1000):
        self.min_size = min_size
        self.max_size = max_size

    def __call__(self, in_data):
        img, bbox, label = in_data
        _, H, W = img.shape
        img = preprocess(img, self.min_size, self.max_size)
        _, o_H, o_W = img.shape
        scale = o_H / H
        bbox = util.resize_bbox(bbox, (H, W), (o_H, o_W))

        # horizontally flip
        img, params = util.random_flip(
            img, x_random=True, return_param=True)
        bbox = util.flip_bbox(
            bbox, (o_H, o_W), x_flip=params['x_flip'])

        return img, bbox, label, scale


class Dataset:
    def __init__(self, opt):
        self.opt = opt
        self.db = VOCBboxDataset(opt.voc_data_dir)
        self.tsf = Transform(opt.min_size, opt.max_size)

    def __getitem__(self, idx):
        ori_img, bbox, label, difficult = self.db.get_example(idx)

        img, bbox, label, scale = self.tsf((ori_img, bbox, label))
        # TODO: check whose stride is negative to fix this instead copy all
        # some of the strides of a given numpy array are negative.
        return img.copy(), bbox.copy(), label.copy(), scale

    def __len__(self):
        return len(self.db)


class TestDataset:
    def __init__(self, opt, split='test', use_difficult=True):
        self.opt = opt
        self.db = VOCBboxDataset(opt.voc_data_dir, split=split, use_difficult=use_difficult)

    def __getitem__(self, idx):
        ori_img, bbox, label, difficult = self.db.get_example(idx)
        img = preprocess(ori_img)
        return img, ori_img.shape[1:], bbox, label, difficult

    def __len__(self):
        return len(self.db)
```

**Comment by yangninghua** [comment]
![image](https://user-images.githubusercontent.com/32252319/68022922-b0c3b300-fce0-11e9-8f18-c872c68db4c1.png)
看不到可视化图的时候注意切换，

**Comment by yangninghua** [comment]
有两个选项，默认是main，所以不显示，取消main，选中fasterrcnn

**Comment by yangninghua** [comment]
https://github.com/chenyuntc/simple-faster-rcnn-pytorch/issues/119
```
@evilidol @Stephenfang51
非常感谢两位大神，pin_memory改成False之后完美运行不再卡死啦
总结一下遇到训练前几个epoch时卡死的问题：
1.根目录 ---> utils ---> config.py 将文件中相应变量改为 num_workers = 0，test_num_workers = 0
2.根目录 ---> train.py 在train()函数中的test_dataloader(pin_memory=False), 或直接删除pin_memory参数即可
应该是电脑的GPU显存或者内存不能同时处理多线程等问题引起的错误，更改参数减小电脑压力即可

For people who doesn't speak chinese:
Thanks so much for helping~
problem: when run the train.py , system kills the terminal or just crash, try following:

root ---> utils ---> config.py change the corresponding varible to num_workers = 0，test_num_workers = 0
root---> train.py, look at the function train(), change to test_dataloader(pin_memory=False),or just comment out pin_memory and you will be fine.
```

**Comment by yangninghua** [comment]
出现如下警告，是因为你没有启动服务
应该先启动服务再运行
nohup python -m visdom.server &
```
load data
model construct completed
Exception in user code:
------------------------------------------------------------
Setting up a new session...
Traceback (most recent call last):
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6ec768d2e8>: Failed to establish a new connection: [Errno 111] Connection refused
```

**Comment by shida666** [comment]
> ![image](https://user-images.githubusercontent.com/32252319/68022922-b0c3b300-fce0-11e9-8f18-c872c68db4c1.png)
> 看不到可视化图的时候注意切换，

你好大佬 你分享的图片打不开  我也是打不开http://<ip>:8097  看不到可视化图 请问您怎么解决的

**Comment by shida666** [comment]
> 有两个选项，默认是main，所以不显示，取消main，选中fasterrcnn

你好大佬  我也是打不开http://:8097 看不到可视化图 请问怎么选中fasterrcnn
