### ISSUE TITLE
Code randomly crashes after some iterations.

### ISSUE THREAD

**Issue by joeybose** [chenyuntc/simple-faster-rcnn-pytorch#16]
So I've tried running the code on my own dataset, but it crashes randomly after a few 1000 iterations. I'm having a hard time debugging this but heres the output:

load data
model construct completed
99it [00:18,  5.41it/s]model/faster_rcnn.py:223: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  img = t.autograd.Variable(at.totensor(img).float()[None], volatile=True)
279it [00:49,  5.62it/s]model/utils/bbox_tools.py:183: RuntimeWarning: invalid value encountered in divide
  return area_i / (area_a[:, None] + area_b - area_i)
model/utils/creator_tool.py:108: RuntimeWarning: invalid value encountered in greater_equal
  pos_index = np.where(max_iou >= self.pos_iou_thresh)[0]
model/utils/creator_tool.py:116: RuntimeWarning: invalid value encountered in less
  neg_index = np.where((max_iou < self.neg_iou_thresh_hi) &
model/utils/creator_tool.py:117: RuntimeWarning: invalid value encountered in greater_equal
  (max_iou >= self.neg_iou_thresh_lo))[0]
model/utils/bbox_tools.py:138: RuntimeWarning: divide by zero encountered in log
  dh = xp.log(base_height / height)
model/utils/bbox_tools.py:139: RuntimeWarning: divide by zero encountered in log
  dw = xp.log(base_width / width)
280it [00:49,  5.62it/s]model/utils/creator_tool.py:411: RuntimeWarning: invalid value encountered in greater_equal
  keep = np.where((hs >= min_size) & (ws >= min_size))[0]
12880it [28:03,  7.65it/s][[B
2097it [02:02, 17.14it/s]Traceback (most recent call last):
  File "train.py", line 123, in <module>
    fire.Fire()
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 103, in train
    eval_result = eval(test_dataloader, faster_rcnn, test_num=opt.test_num)
  File "train.py", line 29, in eval
    pred_bboxes_, pred_labels_, pred_scores_ = faster_rcnn.predict(imgs, [sizes])
  File "model/faster_rcnn.py", line 225, in predict
    roi_cls_loc, roi_scores, rois, _ = self(img, scale=scale)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "model/faster_rcnn.py", line 126, in forward
    h, rois, roi_indices)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "model/faster_rcnn_vgg16.py", line 136, in forward
    rois = at.totensor(rois).float()
  File "model/utils/array_tool.py", line 25, in totensor
    tensor = tensor.cuda()
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 172, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 24699) is killed by signal: Killed.

**Comment by chenyuntc** [comment]
It seems that you are consuming too much resource in dataloader. 
You may also refer to #10 . `eval` is really memory-consuming, you may remove it if it's not necessary.

**Comment by joeybose** [comment]
Yea it looks like the the test data loader has a default size much larger than the actual one causing memory issues. Thanks for the fix.
