### ISSUE TITLE
module 'torch' has no attribute '_TensorBase'

### ISSUE THREAD

**Issue by woxihuanchirou** [chenyuntc/simple-faster-rcnn-pytorch#42]
when I run train.py,it occured that:

```
Traceback (most recent call last):
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9c8347a2b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/htu/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/htu/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c8347a2b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/visdom/__init__.py", line 261, in _send
    data=json.dumps(msg),
  File "/home/htu/.local/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/htu/.local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/htu/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/htu/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/htu/.local/lib/python3.5/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c8347a2b0>: Failed to establish a new connection: [Errno 111] Connection refused',))
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    fire.Fire()
  File "/home/htu/.local/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/htu/.local/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/htu/.local/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 78, in train
    scale = at.scalar(scale)
  File "/home/htu/yc/simple-faster-rcnn-pytorch-master/utils/array_tool.py", line 43, in scalar
    if isinstance(data, t._TensorBase):
AttributeError: module 'torch' has no attribute '_TensorBase'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by woxihuanchirou** [comment]
I cant find anything about torch._TensorBase,but torch.cuda.LongTensor,so I change utils/array_tool.py in line 43:
'''
if isinstance(data, t._TensorBase):
'''
with
'''
if isinstance(data, t.cuda.LongTensor):
'''
it occured that:RecursionError: maximum recursion depth exceeded
How to solve it?

**Comment by dami23** [comment]
I have met the same error. The solution is change the t._TensorBase to t._C._TensorBase

**Comment by woxihuanchirou** [comment]
@dami23 thank you for replying.
I have changed it alright,but a new error occured like this:
```
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    fire.Fire()
  File "/home/htu/.local/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/htu/.local/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/htu/.local/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 81, in train
    trainer.train_step(img, bbox, label, scale)
  File "/home/htu/yc/simple-faster-rcnn-pytorch-master/trainer.py", line 168, in train_step
    losses = self.forward(imgs, bboxes, labels, scale)
  File "/home/htu/yc/simple-faster-rcnn-pytorch-master/trainer.py", line 135, in forward
    self.rpn_sigma)
  File "/home/htu/yc/simple-faster-rcnn-pytorch-master/trainer.py", line 253, in _fast_rcnn_loc_loss
    loc_loss /= (gt_label >= 0).sum()  # ignore gt_label==-1 for rpn_loss
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #3 'other'
```

**Comment by rxqy** [comment]
I am also encountering a similar problem here. 
I followed @dami23 , then changed the line  [ loc_loss /= (gt_label >= 0).sum() ] to  [ loc_loss /= (gt_label >= 0).sum().float() ].

**Comment by rxqy** [comment]
Also, I'm guessing another problem you will gonna encounter  is something like 'Can't call numpy() on Variable'
I changed line 11 from array_tool.py 
` if isinstance(data, t._C._TensorBase):`
to 
` if isinstance(data, t._C._TensorBase) and (data.requires_grad==False): ` 
I don't know if it's an error with pytorch or not, but it works for now

**Comment by woxihuanchirou** [comment]
@rxqy I have already run `pip install -r requirements.txt` without errors.Then I run `python3 build.py build_ext --inplace`,a warning occured like this:
```
running build_ext
cythoning _nms_gpu_post.pyx to _nms_gpu_post.c
building '_nms_gpu_post' extension
creating build
creating build/temp.linux-x86_64-3.5
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c _nms_gpu_post.c -o build/temp.linux-x86_64-3.5/_nms_gpu_post.o
In file included from /usr/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/numpy/ndarrayobject.h:18,
                 from /usr/include/numpy/arrayobject.h:4,
                 from _nms_gpu_post.c:566:
/usr/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/_nms_gpu_post.o -o /home/htu/yc/simple-faster-rcnn-pytorch-master/model/utils/nms/_nms_gpu_post.cpython-35m-x86_64-linux-gnu.so
```
I think it won't trouble me,yes?
Then I run `python3 train.py train --env='fasterrcnn_caffe' --plot_every=100 --caffe_pretrain`,the AttributeError occured again~
It really troubles me a lot! The version of my Python  is 3.5.2.Is it because of this problem?

**Comment by rxqy** [comment]
Sorry but I didn't build this gpu version of nms, I just skipped that step.
About the attribute error,  you might want to refer to this link from pytorch forum.
[https://discuss.pytorch.org/t/question-about-rebuild-tensor-v2/14560/4](url)

I think all these errors are coming from the different versions of pytorch....
Maybe switch to a 0.3 may help..

**Comment by zhuotest** [comment]
The reference url is https://discuss.pytorch.org/t/question-about-rebuild-tensor-v2/14560/2
```python
# Monkey-patch because I trained with a newer version.
# This can be removed once PyTorch 0.4.x is out.
# See https://discuss.pytorch.org/t/question-about-rebuild-tensor-v2/14560
import torch._utils
try:
    torch._utils._rebuild_tensor_v2
except AttributeError:
    def _rebuild_tensor_v2(storage, storage_offset, size, stride, requires_grad, backward_hooks):
        tensor = torch._utils._rebuild_tensor(storage, storage_offset, size, stride)
        tensor.requires_grad = requires_grad
        tensor._backward_hooks = backward_hooks
        return tensor
    torch._utils._rebuild_tensor_v2 = _rebuild_tensor_v2
```

**Comment by perry0418** [comment]
In my case, under the torch 0.4.1, I occur another similar error:
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchnet/meter/averagevaluemeter.py", line 29, in add
    self.std = np.sqrt(self.m_s / (self.n - 1.0))
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 397, in __array__
    return self.cpu().numpy()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

As disscussed in this link: https://github.com/pytorch/pytorch/issues/7610
numpy tries to call the __array__ in tensor.py and the raise the error

so I change the __array__ in site-packages/torch/tensor.py in line 397 as follows:
    def __array__(self, dtype=None):
        if dtype is None:
            if (self.requires_grad==False):
                return self.cpu().numpy()        
            else:
                return self.data.cpu().numpy()
        else:
            return self.cpu().numpy().astype(dtype, copy=False)
It works for me, and it may be helpful for others.
