### ISSUE TITLE
cupy.8.0 problem

### ISSUE THREAD

**Issue by lxtGH** [chenyuntc/simple-faster-rcnn-pytorch#77]
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from model import FasterRCNNVGG16
  File "/home/lxt/cvpr2019-video/simple-faster-rcnn-pytorch/model/__init__.py", line 1, in <module>
    from model.faster_rcnn_vgg16 import FasterRCNNVGG16
  File "/home/lxt/cvpr2019-video/simple-faster-rcnn-pytorch/model/faster_rcnn_vgg16.py", line 5, in <module>
    from model.region_proposal_network import RegionProposalNetwork
  File "/home/lxt/cvpr2019-video/simple-faster-rcnn-pytorch/model/region_proposal_network.py", line 7, in <module>
    from model.utils.creator_tool import ProposalCreator
  File "/home/lxt/cvpr2019-video/simple-faster-rcnn-pytorch/model/utils/creator_tool.py", line 5, in <module>
    from model.utils.nms import non_maximum_suppression
  File "/home/lxt/cvpr2019-video/simple-faster-rcnn-pytorch/model/utils/nms/__init__.py", line 1, in <module>
    from model.utils.nms.non_maximum_suppression import non_maximum_suppression
  File "/home/lxt/cvpr2019-video/simple-faster-rcnn-pytorch/model/utils/nms/non_maximum_suppression.py", line 16, in <module>
    @cp.util.memoize(for_each_device=True)
AttributeError: module 'cupy' has no attribute 'util'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by air-y** [comment]
same proble,do you have solve it?

**Comment by zkqiu** [comment]
same problem,do you have solve it?

**Comment by tkone2018** [comment]
did you solve it?

**Comment by Xxxxxxxi** [comment]
same problem

**Comment by sohee-zoe** [comment]
in my case, cuda version = 10.0
`conda install -c conda-forge cupy==7.8.0 cudatoolkit=10.0`

**Comment by ooza** [comment]
I'm using virtualenv and pip
I've installed cupy-cuda101 and I ran to the same error
any ideas on how to fix this ??

**Comment by ShijianXu** [comment]
Hi @ooza I am meeting with the same problem. I am using cupy-cuda110 (pip virtualenv, conda not allowed). Have you solved this problem?

Thank you very much!
