### ISSUE TITLE
Error when run the train by removing the visualization

### ISSUE THREAD

**Issue by dljrichard** [chenyuntc/simple-faster-rcnn-pytorch#84]
I was initially facing the problem for "visdom"
by error message as 

> No handlers could be found for logger "visdom"

I then remove visualization part by 

> python train.py train --caffe-pretrain=False

then error meet as following: 

model/utils/nms/non_maximum_suppression.py:12: UserWarning: 
    the python code for non_maximum_suppression is about 2x slow
    It is strongly recommended to build cython code: 
    `cd model/utils/nms/; python3 build.py build_ext --inplace
  `cd model/utils/nms/; python3 build.py build_ext --inplace''')
======user config========
{'caffe_pretrain': False,
 'caffe_pretrain_path': 'checkpoints/vgg16_torchvision.pth.pth',
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'epoch': 14,
 'load_path': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 8,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 10000,
 'test_num_workers': 8,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': '/home/dljrichard/simple-faster-rcnn-pytorch-master/VOCdevkit/VOC2007',
 'weight_decay': 0.0005}
==========end============
load data
model construct completed
0it [00:00, ?it/s]
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f17e3a961d0>> ignored
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    fire.Fire()
  File "/home/dljrichard/.local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/dljrichard/.local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/dljrichard/.local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 81, in train
    trainer.train_step(img, bbox, label, scale)
  File "trainer.py", line 169, in train_step
    losses = self.forward(imgs, bboxes, labels, scale)
  File "trainer.py", line 100, in forward
    self.faster_rcnn.rpn(features, img_size, scale)
  File "/home/dljrichard/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "model/region_proposal_network.py", line 127, in forward
    scale=scale)
  File "model/utils/creator_tool.py", line 426, in __call__
    thresh=self.nms_thresh)
  File "model/utils/nms/non_maximum_suppression.py", line 70, in non_maximum_suppression
    return _non_maximum_suppression_gpu(bbox, thresh, score, limit)
  File "model/utils/nms/non_maximum_suppression.py", line 82, in _non_maximum_suppression_gpu
    order = cp.arange(n_bbox, dtype=np.int32)
  File "/home/dljrichard/.local/lib/python2.7/site-packages/cupy/creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/core/_kernel.pyx", line 821, in cupy.core._kernel.ufunc.__call__
  File "cupy/util.pyx", line 48, in cupy.util.memoize.decorator.ret
  File "cupy/core/_kernel.pyx", line 612, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 46, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 148, in cupy.core.core.compile_with_cache
  File "/home/dljrichard/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 164, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/home/dljrichard/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/dljrichard/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
CompileException: /home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(55): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(45): error: no suitable constructor exists to convert from "float" to "__half"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(47): error: no suitable constructor exists to convert from "float" to "__half"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(48): error: no suitable constructor exists to convert from "double" to "__half"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(49): error: no suitable constructor exists to convert from "int" to "__half"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(50): error: no suitable constructor exists to convert from "unsigned int" to "__half"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(51): error: no suitable constructor exists to convert from "long long" to "__half"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(52): error: no suitable constructor exists to convert from "unsigned long long" to "__half"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(57): error: no suitable conversion function from "const half" to "float" exists

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(62): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(66): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(66): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(71): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(75): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(79): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(107): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(107): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(108): error: expected a ";"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(109): error: expected a ";"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(110): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(110): error: identifier "y_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(115): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(115): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(116): error: expected a ";"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(117): error: expected a ";"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(119): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(121): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(123): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(123): error: identifier "y_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(125): error: identifier "y_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(126): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(128): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(130): error: identifier "y_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(131): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(133): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(135): error: identifier "ret_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(140): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(140): error: identifier "__half_raw" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(141): error: expected a ";"

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(142): error: identifier "y_raw_" is undefined

/home/dljrichard/.local/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(281): warning: statement is unreachable
          detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]" 
/tmp/tmpe7gBKj/kern.cu(12): here

40 errors detected in the compilation of "/tmp/tmpe7gBKj/kern.cu".

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

I am confused where I am doing wrong? Is the visualization not correctly removed?

**Comment by dljrichard** [comment]
Does the visdom support only python 3+? Because I am on python 2.7.12

**Comment by Oliverwang** [comment]
I also encountered the same problem. Is your problem solved?

**Comment by congxin513** [comment]
same problem

**Comment by sunqiang85** [comment]
same problem, does anyone have a solution

**Comment by omrysendik** [comment]
same problem...

**Comment by air-y** [comment]
same problem

**Comment by karanchawla** [comment]
I think I found out why this error is happening. It seems that Cuda depends on GCC and their versions need to be `compatible`. I.e Cuda 9 supports gcc6, Cuda 8 supports gcc5 ...

I checked that the version of Cuda and GCC were compatible and that the environment variables were rightly set up.

```
export CUDA_HOME=/usr/local/cuda-X.X
export PATH=${CUDA_HOME}/bin:${PATH}
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH
```
This solved the problem for me.
