### ISSUE TITLE
please,why i got these errors when start training?

### ISSUE THREAD

**Issue by hischen** [chenyuntc/simple-faster-rcnn-pytorch#94]
/home/simple-faster-rcnn-pytorch/model/utils/nms/non_maximum_suppression.py:12: UserWarning:
    the python code for non_maximum_suppression is about 2x slow
    It is strongly recommended to build cython code:
    `cd model/utils/nms/; python3 build.py build_ext --inplace
  `cd model/utils/nms/; python3 build.py build_ext --inplace''')
======user config========
{'caffe_pretrain': True,
 'caffe_pretrain_path': '/root/.torch/models/vgg16_caffe.pth',
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'env': 'fasterrcnn-caffe',
 'epoch': 14,
 'load_path': '/root/.torch/models/vgg16_caffe.pth',
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 8,
 'plot_every': 100,
 'port': 8097,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 600,
 'test_num_workers': 8,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': '/home/simple-faster-rcnn-pytorch/data/VOCdevkit/VOC2012/',
 'weight_decay': 0.0005}
==========end============
load data
model construct completed
Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    fire.Fire()
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 71, in train
    trainer.load(opt.load_path)
  File "/home/simple-faster-rcnn-pytorch/trainer.py", line 216, in load
    self.faster_rcnn.load_state_dict(state_dict)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FasterRCNNVGG16:
        Missing key(s) in state_dict: "extractor.0.weight", "extractor.0.bias", "extractor.2.weight", "extractor.2.bias", "extractor.5.weight", "extractor.5.bias", "extractor.7.weight", "extractor.7.bias", "extractor.10.weight", "extractor.10.bias", "extractor.12.weight", "extractor.12.bias", "extractor.14.weight", "extractor.14.bias", "extractor.17.weight", "extractor.17.bias", "extractor.19.weight", "extractor.19.bias", "extractor.21.weight", "extractor.21.bias", "extractor.24.weight", "extractor.24.bias", "extractor.26.weight", "extractor.26.bias", "extractor.28.weight", "extractor.28.bias", "rpn.conv1.weight", "rpn.conv1.bias", "rpn.score.weight", "rpn.score.bias", "rpn.loc.weight", "rpn.loc.bias", "head.classifier.0.weight", "head.classifier.0.bias", "head.classifier.2.weight", "head.classifier.2.bias", "head.cls_loc.weight", "head.cls_loc.bias", "head.score.weight", "head.score.bias".
        Unexpected key(s) in state_dict: "features.0.weight", "features.0.bias", "features.2.weight", "features.2.bias", "features.5.weight", "features.5.bias", "features.7.weight", "features.7.bias", "features.10.weight", "features.10.bias", "features.12.weight", "features.12.bias", "features.14.weight", "features.14.bias", "features.17.weight", "features.17.bias", "features.19.weight", "features.19.bias", "features.21.weight", "features.21.bias", "features.24.weight", "features.24.bias", "features.26.weight", "features.26.bias", "features.28.weight", "features.28.bias", "classifier.1.weight", "classifier.1.bias", "classifier.4.weight", "classifier.4.bias", "classifier.6.weight", "classifier.6.bias".

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by gmt710** [comment]
@hischen Hello,have you solved this problem?

**Comment by GloriaZLQ** [comment]
have you sovled it ?

**Comment by CUGfred** [comment]
i meet same problem , i guess u use the pretrianed model which downloaded in BaiduNetdisk and it doesnt be converted to torchvision-style?

**Comment by charles-wangzi** [comment]
> torchvision-style?

hello，I want to know how can converted to torchvision-style

**Comment by vua** [comment]
Maybe you can get pretrain model from MISC/convert_caffe_pretrain.py
