### ISSUE TITLE
why tuple.index(x): x not in tuple?

### ISSUE THREAD

**Issue by hischen** [chenyuntc/simple-faster-rcnn-pytorch#96]
root@52f54a48a085:/home/simple-faster-rcnn-pytorch# python train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain=False
/home/simple-faster-rcnn-pytorch/model/utils/nms/non_maximum_suppression.py:12: UserWarning:
    the python code for non_maximum_suppression is about 2x slow
    It is strongly recommended to build cython code:
    `cd model/utils/nms/; python3 build.py build_ext --inplace
  `cd model/utils/nms/; python3 build.py build_ext --inplace''')
======user config========
{'caffe_pretrain': False,
 'caffe_pretrain_path': 'checkpoints/vgg16_caffe.pth',
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'env': 'fasterrcnn-caffe',
 'epoch': 14,
 'load_path': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 8,
 'plot_every': 100,
 'port': 8097,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 600,
 'test_num_workers': 8,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': '/home/simple-faster-rcnn-pytorch/data/VOCdevkit/VOC2012/',
 'weight_decay': 0.0005}
==========end============
load data
model construct completed
Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.
0it [00:00, ?it/s]Traceback (most recent call last):
  File "train.py", line 132, in <module>
    fire.Fire()
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 78, in train
    for ii, (img, bbox_, label_, scale) in tqdm(enumerate(dataloader)):
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/simple-faster-rcnn-pytorch/data/dataset.py", line 107, in __getitem__
    ori_img, bbox, label, difficult = self.db.get_example(idx)
  File "/home/simple-faster-rcnn-pytorch/data/voc_dataset.py", line 120, in get_example
    label.append(VOC_BBOX_LABEL_NAMES.index(name))
ValueError: tuple.index(x): x not in tuple

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by haofeng0928** [comment]
have you changed your dataset? if so, change your label of dataset in ./data/voc_dataset.py

**Comment by gmt710** [comment]
@hischen Hello,have you solved this problem?

**Comment by tkone2018** [comment]
delete the .lower( )

**Comment by charles-wangzi** [comment]
> delete the .lower( )
the answer you said can be detailed？

**Comment by myhui0524** [comment]
have you changed your dataset? if so, change your label of dataset in ./data/voc_dataset.py
I have changed the voc_dataset.py, but it will occur sometimes

delete the .lower( )
i have also delete it, but it also has this error

**Comment by myhui0524** [comment]
可以遍历一下XML文件中所有object的名字

**Comment by ChengxuLiu** [comment]
chack your object name, whether they have the Upper letter :
you can change "name = obj.find('name').text.lower().strip()" to "name = obj.find('name').text.strip()"  in voc_dateset.py
